# Generated by Django 5.2.6 on 2025-10-01 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolUserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('school_head', 'School Head')], default='school_head', max_length=32)),
                ('is_primary', models.BooleanField(default=True, help_text='Use to flag the primary school assignment for the user.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='organizations.school')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['school__name', 'user__username'],
                'unique_together': {('user', 'school', 'role')},
            },
        ),
        migrations.CreateModel(
            name='SectionUserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('section_admin', 'Section Admin')], default='section_admin', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='organizations.section')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['section__code', 'user__username'],
                'unique_together': {('user', 'section', 'role')},
            },
        ),
    ]
