# Generated by Django 5.2.6 on 2025-09-30 04:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SMEAProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=255)),
                ('area_of_concern', models.CharField(blank=True, max_length=255)),
                ('conference_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='FormTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('version', models.CharField(blank=True, max_length=16)),
                ('period_type', models.CharField(choices=[('month', 'Month'), ('quarter', 'Quarter'), ('semester', 'Semester')], default='quarter', max_length=16)),
                ('open_at', models.DateField()),
                ('close_at', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('schema_descriptor', models.JSONField(blank=True, default=dict)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forms', to='organizations.section')),
            ],
            options={
                'ordering': ['section__code', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=64)),
                ('school_year_start', models.PositiveIntegerField()),
                ('quarter', models.CharField(choices=[('Q1', 'Q1'), ('Q2', 'Q2'), ('Q3', 'Q3'), ('Q4', 'Q4')], max_length=2)),
                ('starts_on', models.DateField(blank=True, null=True)),
                ('ends_on', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-school_year_start', 'quarter'],
                'unique_together': {('school_year_start', 'quarter')},
            },
        ),
        migrations.CreateModel(
            name='SMEAActivityRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.TextField()),
                ('output_target', models.TextField(blank=True)),
                ('output_actual', models.TextField(blank=True)),
                ('timeframe_target', models.TextField(blank=True)),
                ('timeframe_actual', models.TextField(blank=True)),
                ('budget_target', models.CharField(blank=True, max_length=64)),
                ('budget_actual', models.CharField(blank=True, max_length=64)),
                ('interpretation', models.TextField(blank=True)),
                ('issues_unaddressed', models.TextField(blank=True)),
                ('facilitating_factors', models.TextField(blank=True)),
                ('agreements', models.TextField(blank=True)),
                ('row_order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='submissions.smeaproject')),
            ],
            options={
                'ordering': ['row_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('returned', 'Returned'), ('noted', 'Noted')], default='draft', max_length=16)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('returned_remarks', models.TextField(blank=True)),
                ('noted_at', models.DateTimeField(blank=True, null=True)),
                ('noted_remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('form_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='submissions.formtemplate')),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_reports', to=settings.AUTH_USER_MODEL)),
                ('noted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='noted_reports', to=settings.AUTH_USER_MODEL)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='submissions.period')),
                ('returned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returned_reports', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='organizations.school')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('school', 'form_template', 'period')},
            },
        ),
        migrations.AddField(
            model_name='smeaproject',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smea_projects', to='submissions.submission'),
        ),
    ]
