# Generated by Django 5.2.6 on 2025-09-30 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_submission_data'),
    ]

    operations = [
    ]
