# Generated by Django 5.2.6 on 2025-10-01 10:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0004_submissionattachment_alter_period_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form1ADMRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ppas_conducted', models.TextField(blank=True)),
                ('ppas_physical_target', models.PositiveIntegerField(default=0)),
                ('ppas_physical_actual', models.PositiveIntegerField(default=0)),
                ('ppas_physical_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('funds_downloaded', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('funds_obligated', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('funds_unobligated', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('funds_percent_obligated', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('funds_percent_burn_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('q1_response', models.TextField(blank=True)),
                ('q2_response', models.TextField(blank=True)),
                ('q3_response', models.TextField(blank=True)),
                ('q4_response', models.TextField(blank=True)),
                ('q5_response', models.TextField(blank=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form1_adm_rows', to='submissions.submission')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Form1PctHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='form1_pct', to='submissions.submission')),
            ],
        ),
        migrations.CreateModel(
            name='Form1Signatories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prepared_by', models.CharField(blank=True, max_length=255)),
                ('submitted_to', models.CharField(blank=True, max_length=255)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='form1_signatories', to='submissions.submission')),
            ],
        ),
        migrations.CreateModel(
            name='Form1SLPAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1a_summary_text', models.TextField(blank=True)),
                ('root_causes', models.TextField(blank=True)),
                ('best_practices', models.TextField(blank=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='form1_slp_analysis', to='submissions.submission')),
            ],
        ),
        migrations.CreateModel(
            name='Form1SupervisionRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_label', models.CharField(blank=True, max_length=32)),
                ('teachers_supervised_observed_ta', models.PositiveIntegerField(default=0)),
                ('intervention_support_provided', models.TextField(blank=True)),
                ('result', models.TextField(blank=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form1_supervision_rows', to='submissions.submission')),
            ],
            options={
                'ordering': ['grade_label', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Form1PctRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(choices=[('access', 'Access'), ('quality', 'Quality'), ('equity', 'Equity'), ('enabling_mechanisms', 'Enabling Mechanisms')], max_length=32)),
                ('percent', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('action_points', models.TextField()),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='submissions.form1pctheader')),
            ],
            options={
                'ordering': ['area'],
                'unique_together': {('header', 'area')},
            },
        ),
        migrations.CreateModel(
            name='Form1ReadingCRLA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('g1', 'Grade 1'), ('g2', 'Grade 2'), ('g3', 'Grade 3'), ('g4', 'Grade 4'), ('g5', 'Grade 5'), ('g6', 'Grade 6')], max_length=8)),
                ('timing', models.CharField(choices=[('boy', 'Beginning of Year'), ('moy', 'Middle of Year'), ('eoy', 'End of Year')], max_length=8)),
                ('subject', models.CharField(choices=[('english', 'English'), ('filipino', 'Filipino'), ('mother_tongue', 'Mother Tongue')], max_length=16)),
                ('band', models.CharField(choices=[('frustration', 'Frustration'), ('instructional', 'Instructional'), ('independent', 'Independent')], max_length=16)),
                ('count', models.PositiveIntegerField(default=0)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form1_crla', to='submissions.submission')),
            ],
            options={
                'ordering': ['level', 'timing', 'subject', 'band'],
                'unique_together': {('submission', 'level', 'timing', 'subject', 'band')},
            },
        ),
        migrations.CreateModel(
            name='Form1ReadingIntervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('description', models.TextField()),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form1_reading_interventions', to='submissions.submission')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('submission', 'order')},
            },
        ),
        migrations.CreateModel(
            name='Form1ReadingPHILIRI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('g1', 'Grade 1'), ('g2', 'Grade 2'), ('g3', 'Grade 3'), ('g4', 'Grade 4'), ('g5', 'Grade 5'), ('g6', 'Grade 6')], max_length=8)),
                ('timing', models.CharField(choices=[('boy', 'Beginning of Year'), ('moy', 'Middle of Year'), ('eoy', 'End of Year')], max_length=8)),
                ('language', models.CharField(choices=[('english', 'English'), ('filipino', 'Filipino'), ('ilokano', 'Ilokano'), ('others', 'Others')], max_length=32)),
                ('band_4_7', models.PositiveIntegerField(default=0)),
                ('band_5_8', models.PositiveIntegerField(default=0)),
                ('band_6_9', models.PositiveIntegerField(default=0)),
                ('band_10', models.PositiveIntegerField(default=0)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form1_philiri', to='submissions.submission')),
            ],
            options={
                'ordering': ['level', 'timing', 'language'],
                'unique_together': {('submission', 'level', 'timing', 'language')},
            },
        ),
        migrations.CreateModel(
            name='Form1RMAIntervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('description', models.TextField()),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form1_rma_interventions', to='submissions.submission')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('submission', 'order')},
            },
        ),
        migrations.CreateModel(
            name='Form1RMARow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_label', models.CharField(choices=[('k', 'Kinder'), ('g1', 'Grade 1'), ('g2', 'Grade 2'), ('g3', 'Grade 3'), ('g4', 'Grade 4'), ('g5', 'Grade 5'), ('g6', 'Grade 6')], max_length=8)),
                ('enrolment', models.PositiveIntegerField()),
                ('band_below_75', models.PositiveIntegerField(default=0)),
                ('band_75_79', models.PositiveIntegerField(default=0)),
                ('band_80_84', models.PositiveIntegerField(default=0)),
                ('band_85_89', models.PositiveIntegerField(default=0)),
                ('band_90_100', models.PositiveIntegerField(default=0)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form1_rma_rows', to='submissions.submission')),
            ],
            options={
                'ordering': ['grade_label'],
                'unique_together': {('submission', 'grade_label')},
            },
        ),
        migrations.CreateModel(
            name='Form1SLPRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_label', models.CharField(max_length=32)),
                ('enrolment', models.PositiveIntegerField()),
                ('dnme', models.PositiveIntegerField(default=0)),
                ('fs', models.PositiveIntegerField(default=0)),
                ('s', models.PositiveIntegerField(default=0)),
                ('vs', models.PositiveIntegerField(default=0)),
                ('o', models.PositiveIntegerField(default=0)),
                ('top_three_llc', models.TextField(blank=True)),
                ('intervention_plan', models.TextField(blank=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form1_slp_rows', to='submissions.submission')),
            ],
            options={
                'ordering': ['grade_label'],
                'unique_together': {('submission', 'grade_label')},
            },
        ),
        migrations.CreateModel(
            name='Form1SLPTopDNME',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_label', models.CharField(max_length=32)),
                ('count', models.PositiveIntegerField(default=0)),
                ('position', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form1_slp_top_dnme', to='submissions.submission')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('submission', 'position')},
            },
        ),
        migrations.CreateModel(
            name='Form1SLPTopOutstanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_label', models.CharField(max_length=32)),
                ('count', models.PositiveIntegerField(default=0)),
                ('position', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form1_slp_top_outstanding', to='submissions.submission')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('submission', 'position')},
            },
        ),
    ]
