# Generated by Django 5.2.6 on 2025-10-01 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0005_form1admrow_form1pctheader_form1signatories_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('returned', 'Returned'), ('noted', 'Noted')], max_length=16)),
                ('to_status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('returned', 'Returned'), ('noted', 'Noted')], max_length=16)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submission_timeline_entries', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='submissions.submission')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
