# Generated by Django 5.1.2 on 2025-10-16 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0007_form1slprow_subject'),
    ]

    operations = [
        # Drop the previous Form1SLPAnalysis from 0005 to avoid duplicate-table errors on fresh DBs.
        # This intentionally discards old data and is safe for staging/demo environments.
        migrations.DeleteModel(
            name='Form1SLPAnalysis',
        ),

        # Create the new Form1SLPAnalysis model with per-row analysis
        migrations.CreateModel(
            name='Form1SLPAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dnme_factors', models.TextField(
                    blank=True,
                    default='',
                    help_text='What are the root causes why learners did not meet expectations?',
                    verbose_name='Hindering factors for DNME learners'
                )),
                ('fs_factors', models.TextField(
                    blank=True,
                    default='',
                    help_text='What are the root causes why learners are fairly satisfactory?',
                    verbose_name='Hindering factors for FS learners'
                )),
                ('s_practices', models.TextField(
                    blank=True,
                    default='',
                    help_text='What facilitating factors helped these learners?',
                    verbose_name='Best practices for Satisfactory learners'
                )),
                ('vs_practices', models.TextField(
                    blank=True,
                    default='',
                    help_text='What facilitating factors helped these learners?',
                    verbose_name='Best practices for Very Satisfactory learners'
                )),
                ('o_practices', models.TextField(
                    blank=True,
                    default='',
                    help_text='What facilitating factors helped these learners?',
                    verbose_name='Best practices for Outstanding learners'
                )),
                ('overall_strategy', models.TextField(
                    blank=True,
                    default='',
                    help_text='At your level, what particular strategy or intervention can you implement to address learners under DNME?',
                    verbose_name='Overall intervention strategy for DNME learners'
                )),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, blank=True)),
                ('slp_row', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='analysis',
                    to='submissions.form1slprow',
                    help_text='The SLP row this analysis belongs to',
                    null=True,
                    blank=True
                )),
            ],
            options={
                'verbose_name': 'SLP Analysis',
                'verbose_name_plural': 'SLP Analyses',
                'ordering': ['slp_row__grade_label', 'slp_row__subject'],
            },
        ),
    ]
