# Generated by Django 5.1.2 on 2025-10-17 03:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0008_recreate_form1slpanalysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingAssessmentCRLA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('bosy', 'BOSY (Beginning of School Year)'), ('mosy', 'MOSY (Middle of School Year)'), ('eosy', 'EOSY (End of School Year)')], max_length=10)),
                ('level', models.CharField(choices=[('low_emerging', 'Low Emerging'), ('high_emerging', 'High Emerging'), ('developing', 'Developing'), ('transitioning', 'Transitioning')], max_length=20)),
                ('mt_grade_1', models.PositiveIntegerField(default=0, verbose_name='Mother Tongue - Grade I')),
                ('mt_grade_2', models.PositiveIntegerField(default=0, verbose_name='Mother Tongue - Grade II')),
                ('mt_grade_3', models.PositiveIntegerField(default=0, verbose_name='Mother Tongue - Grade III')),
                ('fil_grade_2', models.PositiveIntegerField(default=0, verbose_name='Filipino - Grade II')),
                ('fil_grade_3', models.PositiveIntegerField(default=0, verbose_name='Filipino - Grade III')),
                ('eng_grade_3', models.PositiveIntegerField(default=0, verbose_name='English - Grade III')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crla_assessments', to='submissions.submission')),
            ],
            options={
                'verbose_name': 'CRLA Assessment',
                'verbose_name_plural': 'CRLA Assessments',
                'ordering': ['period', 'level'],
                'unique_together': {('submission', 'period', 'level')},
            },
        ),
        migrations.CreateModel(
            name='ReadingAssessmentPHILIRI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('bosy', 'BOSY (Beginning of School Year)'), ('mosy', 'MOSY (Middle of School Year)'), ('eosy', 'EOSY (End of School Year)')], max_length=10)),
                ('level', models.CharField(choices=[('frustration', 'Frustration'), ('instructional', 'Instructional'), ('independent', 'Independent')], max_length=20)),
                ('eng_grade_4_7', models.PositiveIntegerField(default=0, verbose_name='English - Grade 4/7')),
                ('eng_grade_5_8', models.PositiveIntegerField(default=0, verbose_name='English - Grade 5/8')),
                ('eng_grade_6_9', models.PositiveIntegerField(default=0, verbose_name='English - Grade 6/9')),
                ('eng_grade_10', models.PositiveIntegerField(default=0, verbose_name='English - Grade 10')),
                ('fil_grade_4_7', models.PositiveIntegerField(default=0, verbose_name='Filipino - Grade 4/7')),
                ('fil_grade_5_8', models.PositiveIntegerField(default=0, verbose_name='Filipino - Grade 5/8')),
                ('fil_grade_6_9', models.PositiveIntegerField(default=0, verbose_name='Filipino - Grade 6/9')),
                ('fil_grade_10', models.PositiveIntegerField(default=0, verbose_name='Filipino - Grade 10')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='philiri_assessments', to='submissions.submission')),
            ],
            options={
                'verbose_name': 'PHILIRI Assessment',
                'verbose_name_plural': 'PHILIRI Assessments',
                'ordering': ['period', 'level'],
                'unique_together': {('submission', 'period', 'level')},
            },
        ),
        migrations.CreateModel(
            name='ReadingInterventionNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('description', models.TextField(verbose_name='Intervention Description')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_interventions_new', to='submissions.submission')),
            ],
            options={
                'verbose_name': 'Reading Intervention',
                'verbose_name_plural': 'Reading Interventions',
                'ordering': ['order'],
                'unique_together': {('submission', 'order')},
            },
        ),
    ]
