# Generated by Django 5.1.2 on 2025-10-17 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0009_form1slpllcentry_readingassessmentcrla_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form1SLPLLCEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('llc_description', models.TextField(help_text='Description of the Least Learned Competency')),
                ('intervention', models.TextField(help_text='Intervention plan for this LLC')),
                ('order', models.PositiveSmallIntegerField(help_text='Order of LLC (1-3)')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='period',
            options={'ordering': ['school_year_start', 'display_order', 'id']},
        ),
        migrations.RemoveConstraint(
            model_name='period',
            name='period_unique_school_year_quarter',
        ),
        migrations.AddField(
            model_name='period',
            name='close_date',
            field=models.DateField(blank=True, help_text='Submission deadline', null=True),
        ),
        migrations.AddField(
            model_name='period',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='Order for sorting in charts and dropdowns'),
        ),
        migrations.AddField(
            model_name='period',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this period is active'),
        ),
        migrations.AddField(
            model_name='period',
            name='open_date',
            field=models.DateField(blank=True, help_text='When schools can start submitting', null=True),
        ),
        migrations.AddField(
            model_name='period',
            name='quarter_tag',
            field=models.CharField(blank=True, default='', help_text='Optional tag for filtering (Q1, Q2, Q3, Q4, S1, S2, etc.)', max_length=20),
        ),
        migrations.AlterField(
            model_name='period',
            name='label',
            field=models.CharField(help_text="e.g., 'Q1 Report', 'First Quarter', 'November Submission'", max_length=100),
        ),
        migrations.AlterField(
            model_name='period',
            name='quarter',
            field=models.CharField(blank=True, choices=[('Q1', 'Q1'), ('Q2', 'Q2'), ('Q3', 'Q3'), ('Q4', 'Q4')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='period',
            name='school_year_start',
            field=models.PositiveIntegerField(help_text='e.g., 2025 for SY 2025-2026'),
        ),
        migrations.AddField(
            model_name='form1slpllcentry',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slp_llc_entries', to='submissions.submission'),
        ),
        migrations.AlterUniqueTogether(
            name='form1slpllcentry',
            unique_together={('submission', 'order')},
        ),
    ]
