# Generated by Django 5.1.2 on 2025-10-17 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0010_form1slpllcentry_alter_period_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formtemplate',
            name='quarter_filter',
            field=models.CharField(blank=True, default='', help_text='Quarter tag for filtering (Q1, Q2, Q3, Q4)', max_length=10),
        ),
        migrations.AddField(
            model_name='formtemplate',
            name='school_year',
            field=models.PositiveIntegerField(blank=True, help_text='School year start (e.g., 2025 for SY 2025-2026)', null=True),
        ),
    ]
