# Generated by Django 5.1.2 on 2025-10-17 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0011_formtemplate_quarter_filter_formtemplate_school_year'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='period',
            unique_together={('school_year_start', 'quarter_tag')},
        ),
        migrations.AlterField(
            model_name='period',
            name='label',
            field=models.CharField(help_text="e.g., 'Q1', 'Q2', 'Q3', 'Q4'", max_length=100),
        ),
        migrations.AlterField(
            model_name='period',
            name='quarter_tag',
            field=models.CharField(help_text='Quarter tag (Q1, Q2, Q3, Q4)', max_length=20),
        ),
        migrations.RemoveField(
            model_name='period',
            name='close_date',
        ),
        migrations.RemoveField(
            model_name='period',
            name='ends_on',
        ),
        migrations.RemoveField(
            model_name='period',
            name='open_date',
        ),
        migrations.RemoveField(
            model_name='period',
            name='quarter',
        ),
        migrations.RemoveField(
            model_name='period',
            name='starts_on',
        ),
    ]
