# Generated by Django 5.1.2 on 2025-10-18 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0012_remove_period_dates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form1rmarow',
            name='band_75_79',
        ),
        migrations.RemoveField(
            model_name='form1rmarow',
            name='band_80_84',
        ),
        migrations.RemoveField(
            model_name='form1rmarow',
            name='band_85_89',
        ),
        migrations.RemoveField(
            model_name='form1rmarow',
            name='band_90_100',
        ),
        migrations.RemoveField(
            model_name='form1rmarow',
            name='band_below_75',
        ),
        migrations.AddField(
            model_name='form1rmarow',
            name='at_grade_level',
            field=models.PositiveIntegerField(default=0, help_text='Above 85%', verbose_name='At Grade Level'),
        ),
        migrations.AddField(
            model_name='form1rmarow',
            name='developing_nearly_proficient',
            field=models.PositiveIntegerField(default=0, help_text='50%-74%', verbose_name='Developing - Nearly Proficient'),
        ),
        migrations.AddField(
            model_name='form1rmarow',
            name='emerging_low_proficient',
            field=models.PositiveIntegerField(default=0, help_text='25%-49%', verbose_name='Emerging - Low Proficient'),
        ),
        migrations.AddField(
            model_name='form1rmarow',
            name='emerging_not_proficient',
            field=models.PositiveIntegerField(default=0, help_text='Below 25%', verbose_name='Emerging - Not Proficient'),
        ),
        migrations.AddField(
            model_name='form1rmarow',
            name='transitioning_proficient',
            field=models.PositiveIntegerField(default=0, help_text='75%-84%', verbose_name='Transitioning - Proficient'),
        ),
    ]
