# Generated by Django 5.1.2 on 2025-10-18 04:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0013_rma_proficiency_levels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form1admrow',
            name='funds_downloaded',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Downloaded'),
        ),
        migrations.AlterField(
            model_name='form1admrow',
            name='funds_obligated',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Obligated'),
        ),
        migrations.AlterField(
            model_name='form1admrow',
            name='funds_percent_burn_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='% Age/BUR (Burn Rate)'),
        ),
        migrations.AlterField(
            model_name='form1admrow',
            name='funds_percent_obligated',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='% Obligated'),
        ),
        migrations.AlterField(
            model_name='form1admrow',
            name='funds_unobligated',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Unobligated'),
        ),
        migrations.AlterField(
            model_name='form1admrow',
            name='ppas_conducted',
            field=models.TextField(blank=True, verbose_name='PPAs Conducted'),
        ),
        migrations.AlterField(
            model_name='form1admrow',
            name='ppas_physical_actual',
            field=models.PositiveIntegerField(default=0, verbose_name='Physical Actual'),
        ),
        migrations.AlterField(
            model_name='form1admrow',
            name='ppas_physical_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='% of Actual Accomplishment'),
        ),
        migrations.AlterField(
            model_name='form1admrow',
            name='ppas_physical_target',
            field=models.PositiveIntegerField(default=0, verbose_name='Physical Target'),
        ),
        migrations.AlterField(
            model_name='form1admrow',
            name='q1_response',
            field=models.TextField(blank=True, verbose_name='Q1: Factors that helped facilitate PPAs'),
        ),
        migrations.AlterField(
            model_name='form1admrow',
            name='q2_response',
            field=models.TextField(blank=True, verbose_name='Q2: Do PPAs address intended purpose?'),
        ),
        migrations.AlterField(
            model_name='form1admrow',
            name='q3_response',
            field=models.TextField(blank=True, verbose_name='Q3: PPAs to sustain/enhance'),
        ),
        migrations.AlterField(
            model_name='form1admrow',
            name='q4_response',
            field=models.TextField(blank=True, verbose_name='Q4: PPAs to drop/improve'),
        ),
        migrations.AlterField(
            model_name='form1admrow',
            name='q5_response',
            field=models.TextField(blank=True, verbose_name='Q5: Overall significance of ADM implementation'),
        ),
        migrations.CreateModel(
            name='Form1ADMHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_offered', models.BooleanField(default=True, help_text='Check if your school implements ADM programs', verbose_name='School implements ADM (Alternative Delivery Mode)')),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='form1_adm_header', to='submissions.submission')),
            ],
        ),
    ]
