# Generated by Django 5.1.2 on 2025-10-18 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0014_adm_header_is_offered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readingassessmentphiliri',
            name='eng_grade_4_7',
        ),
        migrations.RemoveField(
            model_name='readingassessmentphiliri',
            name='eng_grade_5_8',
        ),
        migrations.RemoveField(
            model_name='readingassessmentphiliri',
            name='eng_grade_6_9',
        ),
        migrations.RemoveField(
            model_name='readingassessmentphiliri',
            name='fil_grade_4_7',
        ),
        migrations.RemoveField(
            model_name='readingassessmentphiliri',
            name='fil_grade_5_8',
        ),
        migrations.RemoveField(
            model_name='readingassessmentphiliri',
            name='fil_grade_6_9',
        ),
        migrations.AddField(
            model_name='readingassessmentphiliri',
            name='eng_grade_4',
            field=models.PositiveIntegerField(default=0, verbose_name='English - Grade 4'),
        ),
        migrations.AddField(
            model_name='readingassessmentphiliri',
            name='eng_grade_5',
            field=models.PositiveIntegerField(default=0, verbose_name='English - Grade 5'),
        ),
        migrations.AddField(
            model_name='readingassessmentphiliri',
            name='eng_grade_6',
            field=models.PositiveIntegerField(default=0, verbose_name='English - Grade 6'),
        ),
        migrations.AddField(
            model_name='readingassessmentphiliri',
            name='eng_grade_7',
            field=models.PositiveIntegerField(default=0, verbose_name='English - Grade 7'),
        ),
        migrations.AddField(
            model_name='readingassessmentphiliri',
            name='eng_grade_8',
            field=models.PositiveIntegerField(default=0, verbose_name='English - Grade 8'),
        ),
        migrations.AddField(
            model_name='readingassessmentphiliri',
            name='eng_grade_9',
            field=models.PositiveIntegerField(default=0, verbose_name='English - Grade 9'),
        ),
        migrations.AddField(
            model_name='readingassessmentphiliri',
            name='fil_grade_4',
            field=models.PositiveIntegerField(default=0, verbose_name='Filipino - Grade 4'),
        ),
        migrations.AddField(
            model_name='readingassessmentphiliri',
            name='fil_grade_5',
            field=models.PositiveIntegerField(default=0, verbose_name='Filipino - Grade 5'),
        ),
        migrations.AddField(
            model_name='readingassessmentphiliri',
            name='fil_grade_6',
            field=models.PositiveIntegerField(default=0, verbose_name='Filipino - Grade 6'),
        ),
        migrations.AddField(
            model_name='readingassessmentphiliri',
            name='fil_grade_7',
            field=models.PositiveIntegerField(default=0, verbose_name='Filipino - Grade 7'),
        ),
        migrations.AddField(
            model_name='readingassessmentphiliri',
            name='fil_grade_8',
            field=models.PositiveIntegerField(default=0, verbose_name='Filipino - Grade 8'),
        ),
        migrations.AddField(
            model_name='readingassessmentphiliri',
            name='fil_grade_9',
            field=models.PositiveIntegerField(default=0, verbose_name='Filipino - Grade 9'),
        ),
    ]
