# Generated by Django 5.2.6 on 2025-10-18 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0015_remove_readingassessmentphiliri_eng_grade_4_7_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form1rmarow',
            name='grade_label',
            field=models.CharField(choices=[('k', 'Kinder'), ('g1', 'Grade 1'), ('g2', 'Grade 2'), ('g3', 'Grade 3'), ('g4', 'Grade 4'), ('g5', 'Grade 5'), ('g6', 'Grade 6'), ('g7', 'Grade 7'), ('g8', 'Grade 8'), ('g9', 'Grade 9'), ('g10', 'Grade 10')], max_length=8),
        ),
    ]
