# Generated by Django 5.1.2 on 2025-10-31 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0016_alter_form1rmarow_grade_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='form1supervisionrow',
            name='total_teachers',
            field=models.PositiveIntegerField(default=0, help_text='Total number of teachers in the grade/area', verbose_name='Total number of teachers'),
        ),
    ]
