# Generated by Django 5.2.6 on 2025-11-14 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0017_form1supervisionrow_total_teachers'),
    ]

    operations = [
        migrations.AddField(
            model_name='form1slprow',
            name='non_mastery_other',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='form1slprow',
            name='non_mastery_reasons',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
