# Generated by Django 5.2.6 on 2025-11-15 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0018_form1slprow_non_mastery_other_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formtemplate',
            name='reading_timing_override',
            field=models.CharField(blank=True, choices=[('', 'Auto (derive from quarter)'), ('bosy', 'BOSY'), ('mosy', 'MOSY'), ('eosy', 'EOSY')], default='', help_text='Override automatic quarter→reading period mapping. Leave blank to use: Q1→eosy, Q2/Q3→bosy, Q4→mosy.', max_length=10),
        ),
        migrations.CreateModel(
            name='ReadingDifficultyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('bosy', 'BOSY'), ('mosy', 'MOSY'), ('eosy', 'EOSY')], max_length=10)),
                ('grade_label', models.CharField(choices=[('k', 'Kinder'), ('g1', 'Grade 1'), ('g2', 'Grade 2'), ('g3', 'Grade 3'), ('g4', 'Grade 4'), ('g5', 'Grade 5'), ('g6', 'Grade 6'), ('g7', 'Grade 7'), ('g8', 'Grade 8'), ('g9', 'Grade 9'), ('g10', 'Grade 10')], max_length=8)),
                ('data', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_difficulty_plans', to='submissions.submission')),
            ],
            options={
                'verbose_name': 'Reading Difficulty Plan',
                'verbose_name_plural': 'Reading Difficulty Plans',
                'ordering': ['period', 'grade_label'],
                'unique_together': {('submission', 'period', 'grade_label')},
            },
        ),
    ]
